[build]
builder = "NIXPACKS"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.10"


[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 200
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1